### ISSUE TITLE
v1.2.2 is using github.com/rwtodd/Go.Sed  which is a GPL 3.0 license

### ISSUE THREAD

**Issue by ashraf-vazeer** [leodido/go-urn#28]
Hi Leodido,

github.com/leodido/go-urn gets pulled indirectly in our project.
Recently in v1.2.2, you have included github.com/rwtodd/Go.Sed package in go-urn which is GPL 3.0 license.

including GPL v3 licensed code in a project with a permissive license like MIT or Apache version 2.0 can be problematic because it could impose GPL v3 licensing requirements on the entire project, which could limit its commercial use or require the release of its source code.

Hence requesting you to please check if you can replace Go.Sed pkg with any permissive license alternative?

Thanks,
Ashraf

**Comment by leodido** [comment]
Hi @ashraf-vazeer,

that GPLv3 Go module is only used during the building mechanism. Hence, I don't know if the mandatory requirement of licensing all the project source code (which I repeat doesn't use that library) s GPLv3 still applies.

Anyways, if there are non GPLv3 alternatives to Go.Sed I'd be happy to use them. Feel free to suggest any!
